version: "3"
services:
  app:
    tty: true
    stdin_open: true
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/var/www/app
      - public-data:/var/www/app/public
      - tmp-data:/var/www/app/tmp
      - log-data:/var/www/app/log
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - db-data:/var/lib/mysql
  adminer:
    image: adminer:latest
    ports:
      - "7000:8080"
    depends_on:
      - db
  web:
    tty: true
    stdin_open: true
    build:
      context: containers/nginx
    volumes:
      - public-data:/var/www/app/public
      - tmp-data:/var/www/app/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: